name: React CI

on: [push]

jobs:
  build:
    name: Build and unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "18"
      - run: npm install
      - run: npm run build --if-present
